### ISSUE TITLE
New Patch

### ISSUE THREAD

**Issue by sabihismail** [stirante/lol-client-java-api#28]
Hello,

Just to let you know, there's a new patch with a lot of challenge based UI changes. I figure the schema has to be re-analyzed. Specifically, there doesn't seem to be a specific data class structure that handles "/lol-challenges/v1/suggested-challenges/local-player" with the current build, but it does just return some object,

Edit: Another endpoint: "/lol-challenges/v1/challenges/local-player".

Thanks!

**Comment by stirante** [comment]
Turns out swagger files are no longer accessible https://github.com/RiotGames/developer-relations/issues/608
I updated the classes to the last known swagger file in https://github.com/stirante/lol-client-java-api/commit/72e178815c120ca5830a670c26e171ed1a78b3f3.

I'm planning to use https://github.com/magisteriis/riot-games-help-to-swagger-dotnet or write something similar myself soon.
